### ISSUE TITLE
Don't write debug.log

### ISSUE THREAD

**Issue by brandonchinn178** [dlvhdr/diffnav#11]
When running diffnav, I see a `debug.log` file being written to the current directory. It should either go to standard log locations, `/tmp`, or only written if debug mode is enabled

**Comment by brandonchinn178** [comment]
Thank you!

**Comment by aschey** [comment]
I think this is still an issue because the environment variable isn't being checked here: https://github.com/dlvhdr/diffnav/blob/3f9a3cd8008d9a0167feacb8badff692d519ad24/main.go#L38

**Comment by dlvhdr** [comment]
Fixed by #34
