### ISSUE TITLE
Does not work with `git log`

### ISSUE THREAD

**Issue by Myzel394** [dlvhdr/diffnav#28]
I've set up diffnav using:

```.gitconfig
[core]
    pager = diffnav
```

When running `git log`, nothing appears.

## Workaround

Call git log using:

```bash
git --no-pager log
```

**Comment by dlvhdr** [comment]
Hey @Myzel394, this tool is not meant to be used with git log, only `diff`. I suggest not setting it as a pager for all things git, just as the diff pager. See the README for instructions
