### ISSUE TITLE
Version 0.2.5 not building from source

### ISSUE THREAD

**Issue by kemelzaidan** [dlvhdr/diffnav#30]
when trying to build the source version 0.2.5 tar.gz package. I get the following error after downloading the dependencies:

```
# command-line-arguments
./main.go:47:15: undefined: initialFileTreeModel
./main.go:48:17: undefined: initialDiffModel
./main.go:108:41: undefined: diffModel
./main.go:181:39: undefined: diffModel
./main.go:187:39: undefined: diffModel
./main.go:196:30: undefined: diffModel
./main.go:199:28: undefined: ftModel
./main.go:208:28: undefined: ftModel
./main.go:209:37: undefined: diffModel
./main.go:212:7: undefined: errMsg
./main.go:212:7: too many errors
```
**go 1.23.1** linux/amd64 on Manjaro.
`GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"`

**Comment by dlvhdr** [comment]
Hey @kemelzaidan I am unfamiliar with all those flags. Simply running `go build` works for me (you might have to do a `go get` or `go mod tidy` first)

**Comment by kemelzaidan** [comment]
Weird... but I could build it. I've packaged it for the Arch Linux distribution: https://aur.archlinux.org/packages/diffnav

Thanks for the help! :+1:
