### ISSUE TITLE
Use goreleaser

### ISSUE THREAD

**Issue by dlvhdr** [dlvhdr/diffnav#6]

**Comment by Myzel394** [comment]
Is it okay with you if I create a nix flake that installs goreleaser in the ci:cd and this will then release the binaries?

**Comment by dlvhdr** [comment]
Not too familiar with nix, but if it runs goreleaser then sure!

**Comment by dlvhdr** [comment]
I've added goreleaser support. If you want to add nix support feel free to open a PR
