### ISSUE TITLE
Automatic releases

### ISSUE THREAD

**Issue by Myzel394** [dlvhdr/diffnav#8]
Hey, I absolutely love this!

I'd be cool if you could automatically build and release a binary so that others do not need to install Go to run diffnav. If you'd like to, I can set up a GitHub action workflow that does automatic builds for new releases and open a PR.

**Comment by dlvhdr** [comment]
Glad you like it!
My intention is to integrate goreleaser.
If you're up to it I'd be happy to get a contribution.

**Comment by dlvhdr** [comment]
See https://github.com/dlvhdr/diffnav/issues/6
